### ISSUE TITLE
[1.20.1 mohist]在更换潘多拉饰品时服务器崩溃

### ISSUE THREAD

**Issue by Star-Jirachi** [Minecraft-LightLand/CurseOfPandora#1]
[crash-2024-03-19_10.50.01-server.txt](https://github.com/Minecraft-LightLand/CurseOfPandora/files/14644929/crash-2024-03-19_10.50.01-server.txt)

**Comment by lcy0x1** [comment]
和Artifacts有关，加群讨论

**Comment by lcy0x1** [comment]
新版本修复
